---
apiVersion: v1
kind: Template
metadata:
  name: ${APP_NAME}
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ${APP_NAME}
  spec:
    # The name of the ClowdEnvironment providing the services
    envName: ${ENV_NAME}
    testing:
      iqePlugin: ${APP_NAME}
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: True
        private:
          enabled: True
      # Details about running pod
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}     
        command:
        - export-service
        - api_server
        livenessProbe:        
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        resources:
          limits:
            cpu: ${{CPU_LIMIT}}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: ENABLE_CLOUDWATCH_LOGGING
          value: ${ENABLE_CLOUDWATCH_LOGGING}
        - name: OPEN_API_FILE_PATH
          value: ${OPEN_API_FILE_PATH}
        - name: OPEN_API_PRIVATE_PATH
          value: ${OPEN_API_PRIVATE_PATH}
        - name: EXPORT_SERVICE_BUCKET
          value: ${EXPORT_SERVICE_BUCKET}
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: EXPORTS_PSKS
          valueFrom:
            secretKeyRef:
              name: export-service-psks
              key: psk-list
        initContainers:
        - args:
          - export-service
          - migrate_db
          - upgrade
          env:
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: DB_SSLMODE
            value: ${DB_SSLMODE}
          image: ${IMAGE}:${IMAGE_TAG}
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 256Mi

    database:
      name: export-service
      version: 12
    objectStore:
    - ${EXPORT_SERVICE_BUCKET}
    kafkaTopics:
    - replicas: 3
      partitions: 64
      topicName: platform.export.requests

    jobs:
    - name: cleaner
      schedule: ${CLEANER_SCHEDULE}
      restartPolicy: OnFailure
      concurrencyPolicy: Replace
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command:
        - export-service
        - expired_export_cleaner
        env:
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: DB_SSLMODE
          value: ${DB_SSLMODE}
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi


- apiVersion: v1
  kind: Service
  metadata:
    name: export
    labels:
      app: export-service
  spec:
    ports:
    - name: public
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      pod: export-service-service
    sessionAffinity: None
    type: ClusterIP


- apiVersion: v1
  kind: Secret
  metadata:
    name: export-service-psks
    labels:
      app: export-service
  data:
    psk-list: "dGVzdGluZy1hLXBzayx0ZXN0aW5nLWEtcHNrLTI="
  type: Opaque


parameters:
  - name: APP_NAME
    description: Application common name
    required: true
    value: export-service
  - description: Cpu limit of service
    name: CPU_LIMIT
    value: "1"
  - description: memory limit of service
    name: MEMORY_LIMIT
    value: 1Gi
  - name: MIN_REPLICAS
    value: "1"
  - description: Image tag
    name: IMAGE_TAG
    required: true    
  - description: Image name
    name: IMAGE
    value: quay.io/cloudservices/export-service
  - description: Determines Clowder deployment
    name: CLOWDER_ENABLED
    value: "true"
  - description: ClowdEnv Name
    name: ENV_NAME
    requred: false    
  - description: Determines if Cloud Watch logging is enabled
    name: ENABLE_CLOUDWATCH_LOGGING
    value: "false"
  - name: OPEN_API_PRIVATE_PATH
    value: /var/tmp/private.json
  - name: OPEN_API_FILE_PATH
    value: /var/tmp/openapi.json
  - name: EXPORT_SERVICE_BUCKET
    value: exports-bucket
  - name: CLEANER_SCHEDULE
    value: "* 1 * * *"
  - name: EXPORTS_PSKS
    value: testing-a-psk
  - name: LOG_LEVEL
    value: INFO
